management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

  #RabbitMQ connection details
spring:
  rabbitmq:
    host: localhost
    port: 5672
  #     username: guest
  #     password: guest
  zipkin:
    base-url: "http://localhost:9411/"
    enabled: true
  cloud:
    config:
#      port: 8200
#      host: 127.0.0.1
#      scheme: http
#      authentication: token
      token: s.2UoASbr6PBaJ27KyeYFJFZ1d
      uri: http://localhost:8888


logging:
  level:
    org.springframework: DEBUG

