
management:
    security:
      enabled: false
    endpoints:
      web:
        exposure:
          include: "*"

  #RabbitMQ connection details
spring:
  rabbitmq:
    host: localhost
    port: 5672
#     username: guest
#     password: guest
  zipkin:
    base-url: "http://localhost:9411/"
    enabled: true
    

logging:
  level:
    org.springframework: TRACE
