spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
  zipkin:
    base-url: "http://zipkin-server:9411/"
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/