management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: localhost
    port: 5672
  zipkin:
    base-url: "http://localhost:9411/"
    enabled: true

logging:
  level:
    org.springframework: INFO

