management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
#    addresses: rabbitmq:5672
  zipkin:
    base-url: "http://zipkin-server:9411/"
    enabled: true


logging:
  level:
    org.springframework: ERROR

