
management:
    security:
      enabled: false
    endpoints:
      web:
        exposure:
          include:"*"

  #RabbitMQ connection details
  spring:
    rabbitmq:
      host:localhost
      port=5672
      username=guest
      password=guest

logging:
  level:
    org.springframework: TRACE
