server:
  port: 8761
eureka:
  instance:
    hostname: eureka-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    #    addresses: rabbitmq:5672
  zipkin:
    base-url: "http://zipkin-server:9411/"
    enabled: true
